### ISSUE TITLE
Build for php

### ISSUE THREAD

**Issue by MajedDH** [CovenantEyes/sqlcipher-windows#7]
Can sqlcipher-windows be built with php instead of normal sqlite3 extension ?
this is how to do it under linux but i couldn't do it under windows :

http://sqlcipher.net/sqlcipher-for-php

**Comment by 3noch** [comment]
This is simply a pre-configured project for building the sqlcipher libraries. This is a static library, so you'd have to configure it for dynamic loading and then figure out how to load in a library with PHP. That's far outside the scope of this work. Good luck!
